[WIP] Add SGX platform
mesalock-linux/mesapy pull request #1
Opened 2018-06-30 00:53 UTC by MelodyHuibo

This PR add support of SGX platform.

2018-07-02 22:47 UTC, mssun requested changes
Please revise your PR accordingly. Thanks.

2018-07-02 22:47 UTC, mssun commented on lib_pypy/cffi/_embedding.h
> -            assert(old_value[1] == 'N');
Why removing assert? I found that the SGX tlibc has the `assert` function: https://github.com/intel/linux-sgx/blob/master/common/inc/tlibc/assert.h

2018-07-02 22:47 UTC, mssun commented on pypy/goal/targetpypystandalone.py
> +
Do we really have to add these lines?

Is this same as `cd pypy/goal && pypy ../../rpython/bin/rpython -Ojit targetpypystandalone.py --no-allworkingmodules --withmod-_cffi_backend`

2018-07-02 22:47 UTC, mssun commented on pypy/module/operator/tscmp.h
> +#include "/opt/intel/sgxsdk/include/tlibc/wchar.h"
This should be `#include<wchar.h>` (not hard-coded path) and set header path in the Makefile.

2018-07-02 22:47 UTC, mssun commented on pypy/module/posix/__init__.py
> +#        'environ': 'interp_posix.get(space).w_environ',
What's this? Deleted?

2018-07-02 22:47 UTC, mssun commented on pypy/module/sys/initpath.py
> +    char *p = strdup(info.dli_fname);
What???

2018-07-02 22:47 UTC, mssun commented on rpython/translator/c/genc.py
> +    print >> f, '#include "/opt/intel/sgxsdk/include/tlibc/stdio.h"'
Use `<stdio.h>`

2018-07-02 22:47 UTC, mssun commented on rpython/translator/tool/cbuild.py
> +	    if num < 21:
What do you mean by `num < 21`?

2018-07-02 22:47 UTC, mssun commented on pypy/module/sys/initpath.py
> +    char *p = strdup(info.dli_fname);
I think simply concatenating current working directory with "enclave.so" is OK.

2018-07-02 22:47 UTC, mssun commented on rpython/rlib/rgil.py
> -_gil_allocate = llexternal('RPyGilAllocate', [], lltype.Void,
Can we define  the following functions and put `pass` in it to make all changes consistent?

2018-07-02 22:47 UTC, mssun commented on rpython/translator/c/funcgen.py
> +            "/*if (PYPY_HAVE_DEBUG_PRINTS) { fprintf(PYPY_DEBUG_FILE, %s); %s}*/"
Is there any better way to return the generated code? If we cannot delete this OP, how about return an empty string?

2018-07-02 22:47 UTC, mssun commented on rpython/translator/driver.py
> -            self.create_exe()
Is `standalone` required? I do not quite understand the meanings of standalone. I will check it later.

2018-07-02 22:47 UTC, mssun commented on rpython/translator/platform/posix.py
> +                           self.preprocess_include_dirs(eci.include_dirs)] + ["/opt/intel/sgxsdk/include/tlibc", curpath, "/home/melody/sgx_pypy_cffi/Enclave/libffi-3.0.13/x86_64-unknown-linux-gnu/in
Do not hard code path, try to use relative instead.

2018-07-02 22:47 UTC, mssun commented on rpython/translator/c/src/asm_gcc_x86.c
> -        fprintf(stderr, "Old CPU with no SSE2 support, cannot continue.\n"
redefine fprintf: https://stackoverflow.com/questions/11406120/how-do-i-use-a-macro-to-redefine-a-function-in-release-mode

2018-07-02 22:47 UTC, mssun commented on rpython/translator/platform/posix.py
> +            ('CFLAGSEXTRA', '-nostdinc'),
`eci.compile_extra.add()`

2018-07-11 03:52 UTC, MelodyHuibo commented on pypy/goal/targetpypystandalone.py
> +
yes

2018-07-11 03:55 UTC, MelodyHuibo commented on pypy/module/posix/__init__.py
> +#        'environ': 'interp_posix.get(space).w_environ',
it is environ not needed.

2018-07-12 00:17 UTC, MelodyHuibo commented on rpython/translator/tool/cbuild.py
> +	    if num < 21:
in pypy makefile, from module_21.c to module_25.c are compiled to the interpreter so the rest part could use system header files.

2018-07-12 00:18 UTC, MelodyHuibo commented on rpython/rlib/rgil.py
> -_gil_allocate = llexternal('RPyGilAllocate', [], lltype.Void,
yes, already done

2018-07-12 00:18 UTC, MelodyHuibo commented on pypy/module/sys/initpath.py
> +    char *p = strdup(info.dli_fname);
already revise as suggest

2018-07-12 00:20 UTC, MelodyHuibo commented on rpython/translator/c/genc.py
> +    print >> f, '#include "/opt/intel/sgxsdk/include/tlibc/stdio.h"'
done

2018-07-12 00:22 UTC, MelodyHuibo commented on rpython/translator/platform/posix.py
> +                           self.preprocess_include_dirs(eci.include_dirs)] + ["/opt/intel/sgxsdk/include/tlibc", curpath, "/home/melody/sgx_pypy_cffi/Enclave/libffi-3.0.13/x86_64-unknown-linux-gnu/in
Now I use the current directory getcwd but you still need to hardcode the directory.  Otherwise no way to know the path.

2018-07-12 00:22 UTC, MelodyHuibo commented on rpython/translator/platform/posix.py
> +            ('CFLAGSEXTRA', '-nostdinc'),
done

2018-07-12 00:22 UTC, MelodyHuibo commented on lib_pypy/cffi/_embedding.h
> -            assert(old_value[1] == 'N');
add assert back

2018-07-12 02:48 UTC, MelodyHuibo commented on rpython/translator/c/funcgen.py
> +            "/*if (PYPY_HAVE_DEBUG_PRINTS) { fprintf(PYPY_DEBUG_FILE, %s); %s}*/"
yes, just return nothing. Done

2018-07-12 02:48 UTC, MelodyHuibo commented on rpython/translator/c/src/asm_gcc_x86.c
> -        fprintf(stderr, "Old CPU with no SSE2 support, cannot continue.\n"
done.

2018-07-21 02:01 UTC, mssun requested changes
Please change your code according my comments. Thanks.

2018-07-21 02:01 UTC, mssun commented on lib-python/2.7/distutils/command/build_ext.py
> +        ext.include_dirs = ext.include_dirs + [par_dir] + [include_dir] + ["/opt/intel/sgxsdk/include/tlibc"]
`ext.include_dirs = ext.include_dirs + [par_dir] + [include_dir] + ["/opt/intel/sgxsdk/include/tlibc"]` can be simplified as `ext.include_dirs = ext.include_dirs + [par_dir, include_dir, "/opt/intel/sgxsdk/include/tlibc"]`?

2018-07-21 02:01 UTC, mssun commented on pypy/goal/targetpypystandalone.py
> +
Add comments to state why this should be put here for a temporary  work around?

2018-07-21 02:01 UTC, mssun commented on pypy/module/_cffi_backend/embedding.py
> +
This new line makes no sense.

2018-07-21 02:01 UTC, mssun commented on pypy/module/posix/__init__.py
> +#        'environ': 'interp_posix.get(space).w_environ',
Then delete it but not comment it.

2018-07-21 02:01 UTC, mssun commented on pypy/module/sys/initpath.py
> +    char *p = malloc(11);
- check return value of `malloc`
- `memset` allocated memory to set all zero.

2018-07-21 02:01 UTC, mssun commented on rpython/rlib/rgil.py
> +	_gil_allocate()
spaces are different

2018-07-21 02:01 UTC, mssun commented on rpython/rlib/rposix.py
> +            fprintf(stdout, "setting %p returning %p\\n", (void*)_Py_silent_invalid_parameter_handler, ret);
Why do you remove comment of this and following lines?

2018-07-30 21:55 UTC, mssun requested changes
Please update the code according to my comments. Thanks!!!

2018-07-30 21:55 UTC, mssun commented on pypy/module/sys/initpath.py
> +
These two newlines make no sense.

2018-07-30 21:55 UTC, mssun commented on rpython/translator/c/src/g_prerequisite.h
> +#include <src/commondefs.h>
Why changing from `"src/commondefs.h"` to `<src/commondefs.h>`?

2018-07-30 21:55 UTC, mssun commented on sgx/README.md
> +
Authors?

2018-07-30 21:55 UTC, mssun commented on rpython/translator/platform/posix.py
> +	    ('PYPY_A', 'libpypy-c.a'),
Please fix the indentation.

2018-07-30 21:55 UTC, mssun commented on sgx/README.md
> +* Iintel SGX SDK 2.2 for Linux installed
`Iintel` -> `Intel`

2018-07-30 21:55 UTC, mssun commented on sgx/README.md
> +MesaPy SGX SDK aims at helping developers write Intel SGX applications in Python language with memory safty.
`memory safty` => `memory safety`

2018-07-30 21:55 UTC, mssun commented on sgx/README.md
> +* As to Sample code, See README in Sample directory for details.
in the Sample directory

2018-07-30 21:55 UTC, mssun commented on sgx/README.md
> +We provide 3 sample codes to help developers understand how to write Enclave code in Python, these codes are located at Sample directory.
3 => three

2018-07-30 21:55 UTC, mssun commented on sgx/README.md
> +We provide 3 sample codes to help developers understand how to write Enclave code in Python, these codes are located at Sample directory.
at the Sample directory

2018-07-30 21:55 UTC, mssun commented on sgx/README.md
> +* HelloWorld is a very simple sample which run Python print.
runs

2018-07-30 21:55 UTC, mssun commented on sgx/Sample/README.md
> +* Download pypy by using "sudo apt-get install" command in Linux machine
Can you specify the steps in details? Like install PyPy by
```
sudo apt-get install pypy
```

2018-07-30 21:55 UTC, mssun commented on sgx/Sample/README.md
> +* Download MesaPy from our github MesaPy, Choose sgx branch.
Same with previous one, how to "clone" the MesaPy source and how to choose the "sgx branch".

2018-07-30 21:55 UTC, mssun commented on sgx/Sample/README.md
> +* Copy whole ussesion folder content from step 1 to usession folder under directory Enclave, Copy libffi to libffi-3.0.13 folder under directory Enclave.
Why?

2018-07-30 21:55 UTC, mssun commented on sgx/Sgx_App_Enclave/README.md
> +-----------------------------------------
This file is same with the `gx/Sample/README.md` file?

2018-07-31 02:19 UTC, MelodyHuibo commented on rpython/rlib/rposix.py
> +            fprintf(stdout, "setting %p returning %p\\n", (void*)_Py_silent_invalid_parameter_handler, ret);
after redefine the fprintf, don't need to comment this function out, just try to be align with the original code.

2018-07-31 20:54 UTC, MelodyHuibo commented on pypy/module/sys/initpath.py
> +    char *p = malloc(11);
fixed

2018-07-31 20:54 UTC, MelodyHuibo commented on rpython/rlib/rgil.py
> +	_gil_allocate()
fixed

2018-07-31 21:49 UTC, MelodyHuibo commented on pypy/module/sys/initpath.py
> +
fixed

2018-07-31 21:57 UTC, MelodyHuibo commented on sgx/Sample/README.md
> +* Download pypy by using "sudo apt-get install" command in Linux machine
ok

2018-07-31 21:57 UTC, MelodyHuibo commented on sgx/Sample/README.md
> +* Download MesaPy from our github MesaPy, Choose sgx branch.
ok

2018-07-31 21:58 UTC, MelodyHuibo commented on sgx/Sgx_App_Enclave/README.md
> +-----------------------------------------
there are some difference for general use.

2018-07-31 21:59 UTC, MelodyHuibo commented on sgx/README.md
> +* HelloWorld is a very simple sample which run Python print.
fixed

2018-07-31 21:59 UTC, MelodyHuibo commented on sgx/README.md
> +We provide 3 sample codes to help developers understand how to write Enclave code in Python, these codes are located at Sample directory.
fixed

2018-07-31 21:59 UTC, MelodyHuibo commented on sgx/README.md
> +* As to Sample code, See README in Sample directory for details.
fixed

2018-07-31 21:59 UTC, MelodyHuibo commented on sgx/README.md
> +MesaPy SGX SDK aims at helping developers write Intel SGX applications in Python language with memory safty.
fixed

2018-07-31 21:59 UTC, MelodyHuibo commented on sgx/README.md
> +* Iintel SGX SDK 2.2 for Linux installed
fixed

2018-07-31 21:59 UTC, MelodyHuibo commented on rpython/translator/platform/posix.py
> +	    ('PYPY_A', 'libpypy-c.a'),
fixed

2018-07-31 23:08 UTC, MelodyHuibo commented on pypy/module/posix/__init__.py
> +#        'environ': 'interp_posix.get(space).w_environ',
done

2018-07-31 23:23 UTC, MelodyHuibo commented on pypy/module/_cffi_backend/embedding.py
> +
fixed

2018-07-31 23:40 UTC, MelodyHuibo commented on pypy/goal/targetpypystandalone.py
> +
done

2018-08-17 04:19 UTC, mssun reviewed
Additional comments.

2018-08-17 04:19 UTC, mssun commented on rpython/rlib/rposix.py
> +            fprintf(stdout, "setting %p returning %p\\n", (void*)_Py_silent_invalid_parameter_handler, ret);
seems that this line is commented in the original code.

2018-08-17 04:19 UTC, mssun commented on rpython/rlib/rposix.py
> +            fprintf(stdout, "exiting, setting %p returning %p\\n", old_handler, ret);
seems that this line is commented in the original code, also

2018-08-17 04:19 UTC, mssun commented on rpython/translator/c/src/exception.c
> +  fprintf(stderr, "%s %.*s: %s:%ld %s\n", msg,                                                                                            (int)(RPyFetchExceptionType()->ov_name->rs_chars.length),
Can you change these two lines same as the original one? From the diff, I can see some difference in spaces.

2018-09-22 18:12 UTC, mssun commented
Squashed and merged to the `sgx` branch.

2018-09-22 18:12 UTC, closed without merging